# -*- coding: utf-8 -*-
"""patitrones.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wYuIcRm_YS3GZEzRCFgZGFvnKEEwQ-Re
"""

import argparse
import cv2
import os
from matplotlib import pyplot as plt
import numpy as np

image = cv2.imread('pics/A.png')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
gray = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)[1]

cv2.imwrite('a2.png', gray)

img = cv2.imread('a2.png',0)
edges = cv2.Canny(img,20,30)
edges2 = cv2.Canny(img,100,200)
fig = plt.figure(figsize=(75,75))
plt.subplot(131),plt.imshow(img,cmap = 'gray')
plt.title('Original Image'), plt.xticks([]), plt.yticks([])
plt.subplot(132),plt.imshow(edges,cmap = 'gray')
plt.title('Edge Image'), plt.xticks([]), plt.yticks([])
plt.subplot(133),plt.imshow(edges2,cmap = 'gray')
plt.title('Edge Image 2'), plt.xticks([]), plt.yticks([])
plt.show()
